name: Auto Check

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'imgs/'
  schedule:
    - cron: '3,24,42 * * * *'
# watch:
#   types: [started]  # 不需要建议注释掉，star触发浪费额度

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 直接使用系统自带python3，移除setup‑python，省去版本拉取/解压步骤，最快启动
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests

      - name: running checkIn
        run: python3 biliiii.py
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
          COOKIES: ${{ secrets.COOKIES }}
          BILI_UID: ${{ secrets.BILI_UID }}
  
