name: Auto Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'imgs/'
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: started

jobs:
  build:
    name: billld
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: running checnIn
      run: |
        python biliiii.py
      env:
        PUSHPLUS: ${{ secrets.PUSHPLUS }}
        COOKIES: ${{ secrets.COOKIES }}
        CH_IDS: ${{ secrets.CH_IDS }}
        WEIBODATAS: ${{ secrets.WEIBODATAS }}
